key_string = {
    # alphabet lower key
    "KeyboardEvent(a down)" : "a",
    "KeyboardEvent(b down)" : "b",
    "KeyboardEvent(c down)" : "c",
    "KeyboardEvent(d down)" : "d",
    "KeyboardEvent(e down)" : "e",
    "KeyboardEvent(f down)" : "f",
    "KeyboardEvent(g down)" : "g",
    "KeyboardEvent(h down)" : "h",
    "KeyboardEvent(i down)" : "i",
    "KeyboardEvent(j down)" : "j",
    "KeyboardEvent(k down)" : "k",
    "KeyboardEvent(l down)" : "l",
    "KeyboardEvent(m down)" : "m",
    "KeyboardEvent(n down)" : "n",
    "KeyboardEvent(o down)" : "o",
    "KeyboardEvent(p down)" : "p",
    "KeyboardEvent(q down)" : "q",
    "KeyboardEvent(r down)" : "r",
    "KeyboardEvent(s down)" : "s",
    "KeyboardEvent(t down)" : "t",
    "KeyboardEvent(u down)" : "u",
    "KeyboardEvent(v down)" : "v",
    "KeyboardEvent(w down)" : "w",
    "KeyboardEvent(x down)" : "x",
    "KeyboardEvent(y down)" : "y",
    "KeyboardEvent(z down)" : "z",
    # alphabet upper key
    "KeyboardEvent(A down)" : "",
    "KeyboardEvent(B down)" : "",
    "KeyboardEvent(C down)" : "",
    "KeyboardEvent(D down)" : "",
    "KeyboardEvent(E down)" : "",
    "KeyboardEvent(F down)" : "",
    "KeyboardEvent(G down)" : "",
    "KeyboardEvent(H down)" : "",
    "KeyboardEvent(I down)" : "",
    "KeyboardEvent(J down)" : "",
    "KeyboardEvent(K down)" : "",
    "KeyboardEvent(L down)" : "",
    "KeyboardEvent(M down)" : "",
    "KeyboardEvent(N down)" : "",
    "KeyboardEvent(O down)" : "",
    "KeyboardEvent(P down)" : "",
    "KeyboardEvent(Q down)" : "",
    "KeyboardEvent(R down)" : "",
    "KeyboardEvent(S down)" : "",
    "KeyboardEvent(T down)" : "",
    "KeyboardEvent(U down)" : "",
    "KeyboardEvent(V down)" : "",
    "KeyboardEvent(W down)" : "",
    "KeyboardEvent(X down)" : "",
    "KeyboardEvent(Y down)" : "",
    "KeyboardEvent(Z down)" : "",
    # command key
    "KeyboardEvent(ctrl down)" : "",
    "KeyboardEvent(shift down)" : "",
    "KeyboardEvent(caps lock down)" : "",
    "KeyboardEvent(tab down)" : "",
    "KeyboardEvent(` down)" : "",
    "KeyboardEvent(esc down)" : "",
    "KeyboardEvent(left windows down)" : "",
    "KeyboardEvent(alt down)" : "",
    "KeyboardEvent(space down)" : "",
    "KeyboardEvent(backspace down)" : "",
    "KeyboardEvent(right alt down)" : "",
    "KeyboardEvent(menu down)" : "",
    "KeyboardEvent(right ctrl down)" : "",
    "KeyboardEvent(enter down)" : "",
    "KeyboardEvent(right shift down)" : "",
    # number key
    "KeyboardEvent(0 down)" : "",
    "KeyboardEvent(1 down)" : "",
    "KeyboardEvent(2 down)" : "",
    "KeyboardEvent(3 down)" : "",
    "KeyboardEvent(4 down)" : "",
    "KeyboardEvent(5 down)" : "",
    "KeyboardEvent(6 down)" : "",
    "KeyboardEvent(7 down)" : "",
    "KeyboardEvent(8 down)" : "",
    "KeyboardEvent(9 down)" : "",
    # symbol key
    "KeyboardEvent(- down)" : "",
    "KeyboardEvent(= down)" : "",
    "KeyboardEvent(' down)" : "",
    "KeyboardEvent([ down)" : "",
    "KeyboardEvent(] down)" : "",
    "KeyboardEvent(\ down)" : "",
    "KeyboardEvent(; down)" : "",
    "KeyboardEvent(, down)" : "",
    "KeyboardEvent(. down)" : "",
    "KeyboardEvent(/ down)" : "",
    # function key
    "KeyboardEvent(f1 down)" : "",
    "KeyboardEvent(f2 down)" : "",
    "KeyboardEvent(f3 down)" : "",
    "KeyboardEvent(f4 down)" : "",
    "KeyboardEvent(f5 down)" : "",
    "KeyboardEvent(f6 down)" : "",
    "KeyboardEvent(f7 down)" : "",
    "KeyboardEvent(f8 down)" : "",
    "KeyboardEvent(f9 down)" : "",
    "KeyboardEvent(f10 down)" : "",
    "KeyboardEvent(f11 down)" : "",
    "KeyboardEvent(f12 down)" : ""
}

key_string_2 = {
    # alphabet lower key
    "KeyboardEvent(a down)" : "a",
    "KeyboardEvent(b down)" : "b",
    "KeyboardEvent(c down)" : "c",
    "KeyboardEvent(d down)" : "d",
    "KeyboardEvent(e down)" : "e",
    "KeyboardEvent(f down)" : "f",
    "KeyboardEvent(g down)" : "g",
    "KeyboardEvent(h down)" : "h",
    "KeyboardEvent(i down)" : "i",
    "KeyboardEvent(j down)" : "j",
    "KeyboardEvent(k down)" : "k",
    "KeyboardEvent(l down)" : "l",
    "KeyboardEvent(m down)" : "m",
    "KeyboardEvent(n down)" : "n",
    "KeyboardEvent(o down)" : "o",
    "KeyboardEvent(p down)" : "p",
    "KeyboardEvent(q down)" : "q",
    "KeyboardEvent(r down)" : "r",
    "KeyboardEvent(s down)" : "s",
    "KeyboardEvent(t down)" : "t",
    "KeyboardEvent(u down)" : "u",
    "KeyboardEvent(v down)" : "v",
    "KeyboardEvent(w down)" : "w",
    "KeyboardEvent(x down)" : "x",
    "KeyboardEvent(y down)" : "y",
    "KeyboardEvent(z down)" : "z",
    # alphabet upper key
    "KeyboardEvent(A down)" : "",
    "KeyboardEvent(B down)" : "",
    "KeyboardEvent(C down)" : "",
    "KeyboardEvent(D down)" : "",
    "KeyboardEvent(E down)" : "",
    "KeyboardEvent(F down)" : "",
    "KeyboardEvent(G down)" : "",
    "KeyboardEvent(H down)" : "",
    "KeyboardEvent(I down)" : "",
    "KeyboardEvent(J down)" : "",
    "KeyboardEvent(K down)" : "",
    "KeyboardEvent(L down)" : "",
    "KeyboardEvent(M down)" : "",
    "KeyboardEvent(N down)" : "",
    "KeyboardEvent(O down)" : "",
    "KeyboardEvent(P down)" : "",
    "KeyboardEvent(Q down)" : "",
    "KeyboardEvent(R down)" : "",
    "KeyboardEvent(S down)" : "",
    "KeyboardEvent(T down)" : "",
    "KeyboardEvent(U down)" : "",
    "KeyboardEvent(V down)" : "",
    "KeyboardEvent(W down)" : "",
    "KeyboardEvent(X down)" : "",
    "KeyboardEvent(Y down)" : "",
    "KeyboardEvent(Z down)" : "",
    # command key
    "KeyboardEvent(ctrl down)" : "",
    "KeyboardEvent(shift down)" : "",
    "KeyboardEvent(caps lock down)" : "",
    "KeyboardEvent(tab down)" : "",
    "KeyboardEvent(` down)" : "",
    "KeyboardEvent(esc down)" : "",
    "KeyboardEvent(left windows down)" : "",
    "KeyboardEvent(alt down)" : "",
    "KeyboardEvent(space down)" : " ",
    "KeyboardEvent(backspace down)" : "",
    "KeyboardEvent(right alt down)" : "",
    "KeyboardEvent(menu down)" : "",
    "KeyboardEvent(right ctrl down)" : "",
    "KeyboardEvent(enter down)" : "",
    "KeyboardEvent(right shift down)" : "",
    # number key
    "KeyboardEvent(0 down)" : "",
    "KeyboardEvent(1 down)" : "",
    "KeyboardEvent(2 down)" : "",
    "KeyboardEvent(3 down)" : "",
    "KeyboardEvent(4 down)" : "",
    "KeyboardEvent(5 down)" : "",
    "KeyboardEvent(6 down)" : "",
    "KeyboardEvent(7 down)" : "",
    "KeyboardEvent(8 down)" : "",
    "KeyboardEvent(9 down)" : "",
    # symbol key
    "KeyboardEvent(- down)" : "",
    "KeyboardEvent(= down)" : "",
    "KeyboardEvent(' down)" : "",
    "KeyboardEvent([ down)" : "",
    "KeyboardEvent(] down)" : "",
    "KeyboardEvent(\ down)" : "",
    "KeyboardEvent(; down)" : "",
    "KeyboardEvent(, down)" : "",
    "KeyboardEvent(. down)" : "",
    "KeyboardEvent(/ down)" : "",
    # function key
    "KeyboardEvent(f1 down)" : "",
    "KeyboardEvent(f2 down)" : "",
    "KeyboardEvent(f3 down)" : "",
    "KeyboardEvent(f4 down)" : "",
    "KeyboardEvent(f5 down)" : "",
    "KeyboardEvent(f6 down)" : "",
    "KeyboardEvent(f7 down)" : "",
    "KeyboardEvent(f8 down)" : "",
    "KeyboardEvent(f9 down)" : "",
    "KeyboardEvent(f10 down)" : "",
    "KeyboardEvent(f11 down)" : "",
    "KeyboardEvent(f12 down)" : ""
}

key_func = ["KeyboardEvent(A down)",
            "KeyboardEvent(B down)",
            "KeyboardEvent(C down)",
            "KeyboardEvent(D down)",
            "KeyboardEvent(E down)",
            "KeyboardEvent(F down)",
            "KeyboardEvent(G down)",
            "KeyboardEvent(H down)",
            "KeyboardEvent(I down)",
            "KeyboardEvent(J down)",
            "KeyboardEvent(K down)",
            "KeyboardEvent(L down)",
            "KeyboardEvent(M down)",
            "KeyboardEvent(N down)",
            "KeyboardEvent(O down)",
            "KeyboardEvent(P down)",
            "KeyboardEvent(Q down)",
            "KeyboardEvent(R down)",
            "KeyboardEvent(S down)",
            "KeyboardEvent(T down)",
            "KeyboardEvent(U down)",
            "KeyboardEvent(V down)",
            "KeyboardEvent(W down)",
            "KeyboardEvent(X down)",
            "KeyboardEvent(Y down)",
            "KeyboardEvent(Z down)",

            "KeyboardEvent(- down)",
            "KeyboardEvent(space down)",
            "KeyboardEvent(- down)",
            "KeyboardEvent(= down)",
            "KeyboardEvent(' down)",
            "KeyboardEvent([ down)",
            "KeyboardEvent(] down)",
            "KeyboardEvent(\ down)",
            "KeyboardEvent(; down)",
            "KeyboardEvent(, down)",
            "KeyboardEvent(. down)",
            "KeyboardEvent(/ down)",

            "KeyboardEvent(0 down)",
            "KeyboardEvent(1 down)",
            "KeyboardEvent(2 down)",
            "KeyboardEvent(3 down)",
            "KeyboardEvent(4 down)",
            "KeyboardEvent(5 down)",
            "KeyboardEvent(6 down)",
            "KeyboardEvent(7 down)",
            "KeyboardEvent(8 down)",
            "KeyboardEvent(9 down)",
            
            "KeyboardEvent(tab down)",
            "KeyboardEvent(enter down)"]